version: "3.8"
services:
  dev:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: python-opencv:0.0.1
    container_name: python-opencv
    stdin_open: true
    tty: true
    ports:
      - "5900:5900"
      - "8888:8888"
    volumes:
      - ../code:/app/code
      - ../.vscode-server:/root/.vscode-server
